/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Accuracy extends Metric {
  private transient long swigCPtr;

  protected Accuracy(long cPtr, boolean cMemoryOwn) {
    super(singa_wrapJNI.Accuracy_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Accuracy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        singa_wrapJNI.delete_Accuracy(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Tensor Forward(Tensor prediction, Tensor target) {
    return new Tensor(singa_wrapJNI.Accuracy_Forward(swigCPtr, this, Tensor.getCPtr(prediction), prediction, Tensor.getCPtr(target), target), true);
  }

  public Accuracy() {
    this(singa_wrapJNI.new_Accuracy(), true);
  }

}
