/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Metric {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Metric(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Metric obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        singa_wrapJNI.delete_Metric(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Tensor Forward(Tensor prediction, Tensor target) {
    return new Tensor(singa_wrapJNI.Metric_Forward(swigCPtr, this, Tensor.getCPtr(prediction), prediction, Tensor.getCPtr(target), target), true);
  }

  public float Evaluate(Tensor prediction, Tensor target) {
    return singa_wrapJNI.Metric_Evaluate(swigCPtr, this, Tensor.getCPtr(prediction), prediction, Tensor.getCPtr(target), target);
  }

}
