/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class netJNI {
  public final static native long new_FeedForwardNet();
  public final static native long FeedForwardNet_Add__SWIG_0(long jarg1, FeedForwardNet jarg1_, long jarg2);
  public final static native long FeedForwardNet_Add__SWIG_1(long jarg1, FeedForwardNet jarg1_, long jarg2, long jarg3);
  public final static native long FeedForwardNet_GetParamNames(long jarg1, FeedForwardNet jarg1_);
  public final static native long FeedForwardNet_GetParamValues(long jarg1, FeedForwardNet jarg1_);
  public final static native long FeedForwardNet_GetParamSpecs(long jarg1, FeedForwardNet jarg1_);
  public final static native void FeedForwardNet_Compile(long jarg1, FeedForwardNet jarg1_, boolean jarg2, long jarg3, long jarg4, long jarg5);
  public final static native void FeedForwardNet_ToDevice(long jarg1, FeedForwardNet jarg1_, long jarg2);
  public final static native long FeedForwardNet_Clone(long jarg1, FeedForwardNet jarg1_, long jarg2);
  public final static native void FeedForwardNet_AsType(long jarg1, FeedForwardNet jarg1_, long jarg2);
  public final static native long FeedForwardNet_Forward(long jarg1, FeedForwardNet jarg1_, int jarg2, long jarg3);
  public final static native long FeedForwardNet_Backward(long jarg1, FeedForwardNet jarg1_, int jarg2, long jarg3);
  public final static native long FeedForwardNet_Evaluate(long jarg1, FeedForwardNet jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long FeedForwardNet_EvaluateOnBatch(long jarg1, FeedForwardNet jarg1_, long jarg2, long jarg3);
  public final static native long FeedForwardNet_Predict(long jarg1, FeedForwardNet jarg1_, long jarg2, long jarg3);
  public final static native void delete_FeedForwardNet(long jarg1);
}
