/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface singa_wrapConstants {
  public final static int USE_CUDA = singa_wrapJNI.USE_CUDA_get();
  public final static int USE_CUDNN = singa_wrapJNI.USE_CUDNN_get();
  public final static int CUDNN_VERSION_SWIG = singa_wrapJNI.CUDNN_VERSION_SWIG_get();
}
