/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sizePair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sizePair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sizePair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        singa_wrapJNI.delete_sizePair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sizePair() {
    this(singa_wrapJNI.new_sizePair__SWIG_0(), true);
  }

  public sizePair(long first, long second) {
    this(singa_wrapJNI.new_sizePair__SWIG_1(first, second), true);
  }

  public sizePair(sizePair p) {
    this(singa_wrapJNI.new_sizePair__SWIG_2(sizePair.getCPtr(p), p), true);
  }

  public void setFirst(long value) {
    singa_wrapJNI.sizePair_first_set(swigCPtr, this, value);
  }

  public long getFirst() {
    return singa_wrapJNI.sizePair_first_get(swigCPtr, this);
  }

  public void setSecond(long value) {
    singa_wrapJNI.sizePair_second_set(swigCPtr, this, value);
  }

  public long getSecond() {
    return singa_wrapJNI.sizePair_second_get(swigCPtr, this);
  }

}
