/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class tensorVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected tensorVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tensorVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        singa_wrapJNI.delete_tensorVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public tensorVector() {
    this(singa_wrapJNI.new_tensorVector__SWIG_0(), true);
  }

  public tensorVector(long n) {
    this(singa_wrapJNI.new_tensorVector__SWIG_1(n), true);
  }

  public long size() {
    return singa_wrapJNI.tensorVector_size(swigCPtr, this);
  }

  public long capacity() {
    return singa_wrapJNI.tensorVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    singa_wrapJNI.tensorVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return singa_wrapJNI.tensorVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    singa_wrapJNI.tensorVector_clear(swigCPtr, this);
  }

  public void add(Tensor x) {
    singa_wrapJNI.tensorVector_add(swigCPtr, this, Tensor.getCPtr(x), x);
  }

  public Tensor get(int i) {
    return new Tensor(singa_wrapJNI.tensorVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Tensor val) {
    singa_wrapJNI.tensorVector_set(swigCPtr, this, i, Tensor.getCPtr(val), val);
  }

}
