/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ttvecPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ttvecPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ttvecPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        singa_wrapJNI.delete_ttvecPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ttvecPair() {
    this(singa_wrapJNI.new_ttvecPair__SWIG_0(), true);
  }

  public ttvecPair(Tensor first, tensorVector second) {
    this(singa_wrapJNI.new_ttvecPair__SWIG_1(Tensor.getCPtr(first), first, tensorVector.getCPtr(second), second), true);
  }

  public ttvecPair(ttvecPair p) {
    this(singa_wrapJNI.new_ttvecPair__SWIG_2(ttvecPair.getCPtr(p), p), true);
  }

  public void setFirst(Tensor value) {
    singa_wrapJNI.ttvecPair_first_set(swigCPtr, this, Tensor.getCPtr(value), value);
  }

  public Tensor getFirst() {
    long cPtr = singa_wrapJNI.ttvecPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Tensor(cPtr, false);
  }

  public void setSecond(tensorVector value) {
    singa_wrapJNI.ttvecPair_second_set(swigCPtr, this, tensorVector.getCPtr(value), value);
  }

  public tensorVector getSecond() {
    long cPtr = singa_wrapJNI.ttvecPair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tensorVector(cPtr, false);
  }

}
