/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class tvecPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected tvecPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tvecPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        singa_wrapJNI.delete_tvecPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public tvecPair() {
    this(singa_wrapJNI.new_tvecPair__SWIG_0(), true);
  }

  public tvecPair(tensorVector first, tensorVector second) {
    this(singa_wrapJNI.new_tvecPair__SWIG_1(tensorVector.getCPtr(first), first, tensorVector.getCPtr(second), second), true);
  }

  public tvecPair(tvecPair p) {
    this(singa_wrapJNI.new_tvecPair__SWIG_2(tvecPair.getCPtr(p), p), true);
  }

  public void setFirst(tensorVector value) {
    singa_wrapJNI.tvecPair_first_set(swigCPtr, this, tensorVector.getCPtr(value), value);
  }

  public tensorVector getFirst() {
    long cPtr = singa_wrapJNI.tvecPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tensorVector(cPtr, false);
  }

  public void setSecond(tensorVector value) {
    singa_wrapJNI.tvecPair_second_set(swigCPtr, this, tensorVector.getCPtr(value), value);
  }

  public tensorVector getSecond() {
    long cPtr = singa_wrapJNI.tvecPair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tensorVector(cPtr, false);
  }

}
