/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vectorPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        singa_wrapJNI.delete_vectorPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorPair() {
    this(singa_wrapJNI.new_vectorPair__SWIG_0(), true);
  }

  public vectorPair(long n) {
    this(singa_wrapJNI.new_vectorPair__SWIG_1(n), true);
  }

  public long size() {
    return singa_wrapJNI.vectorPair_size(swigCPtr, this);
  }

  public long capacity() {
    return singa_wrapJNI.vectorPair_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    singa_wrapJNI.vectorPair_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return singa_wrapJNI.vectorPair_isEmpty(swigCPtr, this);
  }

  public void clear() {
    singa_wrapJNI.vectorPair_clear(swigCPtr, this);
  }

  public void add(sizePair x) {
    singa_wrapJNI.vectorPair_add(swigCPtr, this, sizePair.getCPtr(x), x);
  }

  public sizePair get(int i) {
    return new sizePair(singa_wrapJNI.vectorPair_get(swigCPtr, this, i), false);
  }

  public void set(int i, sizePair val) {
    singa_wrapJNI.vectorPair_set(swigCPtr, this, i, sizePair.getCPtr(val), val);
  }

}
