/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vectorSharedPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorSharedPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorSharedPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        singa_wrapJNI.delete_vectorSharedPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorSharedPtr() {
    this(singa_wrapJNI.new_vectorSharedPtr__SWIG_0(), true);
  }

  public vectorSharedPtr(long n) {
    this(singa_wrapJNI.new_vectorSharedPtr__SWIG_1(n), true);
  }

  public long size() {
    return singa_wrapJNI.vectorSharedPtr_size(swigCPtr, this);
  }

  public long capacity() {
    return singa_wrapJNI.vectorSharedPtr_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    singa_wrapJNI.vectorSharedPtr_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return singa_wrapJNI.vectorSharedPtr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    singa_wrapJNI.vectorSharedPtr_clear(swigCPtr, this);
  }

  public void add(Device x) {
    singa_wrapJNI.vectorSharedPtr_add(swigCPtr, this, Device.getCPtr(x), x);
  }

  public Device get(int i) {
    long cPtr = singa_wrapJNI.vectorSharedPtr_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Device(cPtr, true);
  }

  public void set(int i, Device val) {
    singa_wrapJNI.vectorSharedPtr_set(swigCPtr, this, i, Device.getCPtr(val), val);
  }

}
